# NetlifyCMS config file
# https://www.netlifycms.org/docs/configuration-options/

backend:
  # Use Netlify Identity as backend
  name: git-gateway
  branch: main
media_folder: "src/site/assets/media"
public_folder: "/assets/media"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
display_url: /en/

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
- label: ‹Dictionary i18n›
  name: fragments
  i18n:
    structure: single_file
  files:
    - label: Global text fragments
      name: i18n-globals
      file: src/site/_data/i18n/globals.json
      i18n: true
      fields:
        - { label: Contact, name: contact, widget: string, i18n: true }
        - { label: About, name: about, widget: string, i18n: true }
        - { label: Home, name: home, widget: string, i18n: true }
        - { label: Blog, name: blog, widget: string, i18n: true }
        - { label: Strategy, name: strategy, widget: string, i18n: true }
        - { label: Media, name: media, widget: string, i18n: true }
        - { label: Impressum, name: impressum, widget: string, i18n: true }
    - label: Signup text fragments
      name: i18n-signup
      file: src/site/_data/i18n/signup.json
      i18n: true
      fields:
        - { label: Title, name: title, widget: string, i18n: true }
        - { label: "First name", name: first_name, widget: string, i18n: true }
        - { label: "Last name", name: last_name, widget: string, i18n: true }
        - { label: "Email address", name: email, widget: string, i18n: true }

- label: ‹Projects›
  name: project
  folder: src/site/_project
  create: true
  extension: md
  editor:
    preview: false
  i18n: true
  identifier_field: id
  fields:
    - {label: "Id (never change this, only set a unique value at creation)", name: id, widget: string, }
    - {label: Name, name: name, widget: string, i18n: true}
    - {label: Description, name: description, widget: markdown, i18n: true }
    - {label: Image, name: image, widget: image, i18n: true}
    - {label: Url, name: url, widget: file, i18n: true}


- label: Home (main page)
  name: home
  # Configure i18n for this collection.
  folder: src/site/home
  extension: html
  editor:
    preview: false
  create: false
  i18n:
    structure: multiple_folders
  preview_path: /en/
  fields:
    - { label: "Browser tab title", name: title, widget: string, i18n: true }
    - { label: Hero , name: hero, widget: markdown, i18n: true }
    - { label: "Paragraph 1 title", name: paragraph1_title, widget: string, i18n: true }
    - { label: "Problem title", name: problem_title, widget: string, i18n: true }
    - { label: "Problem description", name: problem_description, widget: markdown, i18n: true }
    - { label: "Strategy title", name: strategy_title, widget: string, i18n: true }
    - { label: "Strategy description", name: strategy_description, widget: markdown, i18n: true }
    - { label: "Strategy link text", name: strategy_link_text, widget: string, i18n: true }
    - { label: "Join title", name: join_title, widget: string, i18n: true }
    - { label: "Join description", name: join_description, widget: markdown, i18n: true }
    - { label: "Join link text", name: join_link_text, widget: string, i18n: true }
    - { label: "Partners title", name: partners_title, widget: string, i18n: true }
    - { label: "Partners description", name: partners_description, widget: markdown, i18n: true }
    - { label: "Partners link text", name: partners_link_text, widget: string, i18n: true }
    - { label: "Projects title", name: projects_title, widget: string, i18n: true }
    - label: "Projects"
      name: "featured_projects"
      widget: "list"
      field:
        name: "Project"
        widget: relation
        collection: project
        value_field: "id"
        display_fields: ["name"]
        multiple: false
        search_fields: ["name", "description"]
    - { label: "News title", name: news_title, widget: string, i18n: true }
    - label: "News items"
      name: "news"
      widget: "list"
      i18n: true
      field:
        name: "Editorial"
        widget: relation
        collection: editorials
        value_field: "id"
        display_fields: ["title"]
        multiple: false
        search_fields: ["title", "body"]

# projects...
# relations (news & events):
# - post1: post
# - post2: post
# - post3: post
#

- label: Home › About us
  name: about
  folder: src/site/about
  extension: md
  editor:
    preview: false
  create: false
  i18n: true
  preview_path: /en/about/
  fields:
    - { label: "Browser tab title", name: title, widget: string, i18n: true }
    - { label: Hero , name: hero, widget: markdown, i18n: true }
    - { label: "Story title", name: story_title, widget: string, i18n: true }
    - { label: "Story", name: story, widget: markdown, i18n: true }
    - { label: "Contact title", name: contact_title, widget: string, i18n: true }
    - { label: "Contact project", name: contact_project, widget: string, i18n: true }
    - { label: "Contact project action", name: contact_project_action, widget: string, i18n: true }
    - { label: "Contact sharer", name: contact_sharer, widget: string, i18n: true }
    - { label: "Contact sharer action", name: contact_sharer_action, widget: string, i18n: true }
    - { label: "Contact media", name: contact_media, widget: string, i18n: true }
    - { label: "Contact media action", name: contact_media_action, widget: string, i18n: true }
    - { label: "Contact other", name: contact_other, widget: string, i18n: true }
    - { label: "People title", name: people_title, widget: string, i18n: true }
    - label: "People"
      name: "people"
      widget: "list"
      i18n: true
      summary: '{{fields.name}}'
      fields:
        - {label: Name, name: name, widget: string}
        - {label: Description, name: description, widget: text }
    - { label: "Timeline title", name: timeline_title, widget: string, i18n: true }
    - label: "Timeline events"
      name: "timeline_events"
      widget: "list"
      i18n: true
      summary: '{{fields.name}}'
      fields:
        - {label: "Date", name: name, widget: date}
        - {label: Description, name: description, widget: text }

- label: Home › Impressum
  name: impressum
  folder: src/site/impressum
  extension: md
  editor:
    preview: false
  create: false
  i18n: true
  preview_path: /en/impressum/
  fields:
    - { label: "Browser tab title", name: title, widget: string, i18n: true }
    - { label: Hero , name: hero, widget: markdown, i18n: true }
    - { label: Body , name: body, widget: markdown, i18n: true }
- label: Home › Media
  name: media
  folder: src/site/media
  extension: md
  editor:
    preview: false
  create: false
  i18n: true
  preview_path: /en/media/
  fields:
    - { label: "Browser tab title", name: title, widget: string, i18n: true }
    - { label: Hero , name: hero, widget: markdown, i18n: true }
    - { label: "Articles title" , name: articles_title , widget: text, i18n: true }
    - { label: "Read button" , name: read_button , widget: text, i18n: true }
    - { label: "Contact title" , name: contact_title , widget: text, i18n: true }
    - { label: "Contact email" , name: contact_email , widget: text, i18n: true }
    - { label: "Media kit title" , name: media_kit_title , widget: text, i18n: true }
    - { label: "Media kit file" , name: media_kit_file , widget: file, i18n: true }
    - { label: "Download title" , name: download_title , widget: text, i18n: true }
    - { label: "Download button" , name: download_button , widget: text, i18n: true }
    - label: "Media articles"
      name: "media_articles"
      widget: "list"
      i18n: true
      summary: '{{fields.title}}'
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Date, name: date, widget: date}
        - {label: Publication, name: publication, widget: text }
        - {label: Lead, name: lead, widget: text }
        - {label: Article, name: url, widget: file }
        - {label: Image, name: image, widget: "image"}
    - { label: "Press releases title" , name: press_releases_title , widget: text, i18n: true }
    - label: "Press releases"
      name: "press_releases"
      widget: "list"
      i18n: true
      summary: '{{fields.title}}'
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Date, name: date, widget: date}
        - {label: File, name: url, widget: file }

- label: Home › Strategy
  name: strategy
  folder: src/site/strategy
  extension: md
  editor:
    preview: false
  create: false
  i18n: true
  preview_path: /en/strategy/
  fields:
    - { label: "Browser tab title", name: title, widget: string, i18n: true }
    - { label: Hero , name: hero, widget: markdown, i18n: true }
    - { label: "Introduction title" , name: introduction_title , widget: text, i18n: true }
    - { label: Introduction , name: introduction, widget: markdown, i18n: true }
    - { label: "Manifesto button" , name: manifesto_button , widget: text, i18n: true }
    - { label: "Manifesto" , name: manifesto_file , widget: file, i18n: true }
    - { label: "Submit button (small)" , name: submit_button_small , widget: text, i18n: true }
    - { label: "Submit button (big)" , name: submit_button_big , widget: text, i18n: true }
    - { label: "Four steps title" , name: four_steps_title , widget: text, i18n: true }
    - { label: "Four steps introduction" , name: four_steps_introduction, widget: markdown, i18n: true }
    - label: "Change steps"
      name: "change_steps"
      widget: "list"
      i18n: true
      summary: '{{fields.title}}'
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Description, name: description, widget: markdown }
        - {label: Image, name: image, widget: "image"}
    - { label: "Conclusion title" , name: conclusion_title , widget: text, i18n: true }
    - { label: Conclusion , name: conclusion, widget: markdown, i18n: true }

- label: Home › Partners
  name: partners
  folder: src/site/partners
  extension: md
  editor:
    preview: false
  create: true
  i18n: true
  preview_path: /en/partners/
  fields:
    - { label: "Browser tab title", name: title, widget: string, i18n: true }
    - { label: Hero , name: hero, widget: markdown, i18n: true }
    - { label: "You › title" , name: you_title , widget: text, i18n: true }
    - {label: "You › image", name: you_image, widget: "image", i18n: true }
    - { label: "You › description" , name: you_description, widget: markdown, i18n: true }
    - { label: "You › button" , name: you_button , widget: text, i18n: true }
    - label: "Partners"
      name: "partners"
      widget: "list"
      i18n: true
      summary: '{{fields.title}}'
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Description, name: description, widget: markdown }
        - {label: Website, name: website, widget: file}
        - {label: Image, name: image, widget: "image"}

- label: Home › Projects (page)
  name: projects_page
  folder: src/site/projects
  extension: md
  editor:
    preview: false
  create: false
  i18n: true
  preview_path: /en/projects/
  fields:
    - { label: "Browser tab title", name: title, widget: string, i18n: true }
    - { label: Hero , name: hero, widget: markdown, i18n: true }
    - { label: "Introduction › title" , name: introduction_title, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
    - { label: "Introduction › content", name: introduction, widget: markdown, i18n: true }
    - { label: "Your project › title", name: your_title, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
    - { label: "Your project › subtitle", name: your_subtitle, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
    - { label: "Your project › button" , name: your_button , widget: text, i18n: true }
    - { label: "Your project › url" , name: your_url , widget: text, i18n: true }
    - { label: "Running project › title" , name: running_projects_title, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
    - { label: "Running project › button" , name: running_projects_button, i18n: true, widget: string}
    - label: "Running projects"
      name: "running_projects"
      widget: "list"
      field:
        name: "Project"
        widget: relation
        collection: project
        value_field: "id"
        display_fields: ["name"]
        multiple: false
        search_fields: ["name", "description"]
    - { label: "Launchpad project › title" , name: launchpad_projects_title, i18n: true,
        widget: markdown, buttons: [bold, italic, link], editor_components: [], minimal: true}
    - { label: "Launchpad project › button" , name: launchpad_projects_button, i18n: true, widget: string}
    - label: "Launchpad projects"
      name: "launchpad_projects"
      widget: "list"
      field:
        name: "Project"
        widget: relation
        collection: project
        value_field: "id"
        display_fields: ["name"]
        multiple: false
        search_fields: ["name", "description"]

- label: Blog (main page)
  name: blog
  # Configure i18n for this collection.
  folder: src/site/blog
  editor:
    preview: false
  create: false
  i18n: true
  preview_path: /en/blog/
  fields:
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: "Lead", name: "lead", widget: "markdown", i18n: true }
    - { label: Editorials title, name: editorials_title, widget: string, i18n: true }
    - { label: Interviews title, name: interviews_title, widget: string, i18n: true }
    - { label: Infographics title, name: infographics_title, widget: string, i18n: true }
    - { label: Categories title, name: categories_title, widget: string, i18n: true }
    - { label: Categories title, name: authors_title, widget: string, i18n: true }

- label: Blog › Editorials
  name: editorials
  folder: src/site/editorial
  extension: md
  editor:
    preview: false
  create: true
  i18n: true
  preview_path: /en/editorial/{{slug}}
  fields:
    - { label: "Id (never change this, only set a unique value at creation)", name: id, widget: string }
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: Date, name: date, widget: datetime, i18n: true }
    - { label: "Image", name: "image", widget: "image", i18n: true }
    - { label: "Lead", name: "lead", widget: "markdown", i18n: true }
    - { label: "Body", name: "body", widget: "markdown", i18n: true }
    - label: "categories"
      name: "post_categories"
      widget: relation
      collection: post_categories
      # i18n: true
      value_field: "id"
      multiple: true
      search_fields: ["name", "id", "description"]
    - label: "author"
      name: "post_authors"
      widget: relation
      collection: post_authors
      # i18n: true
      value_field: "id"
      multiple: true
      search_fields: ["name", "id", "description"]

- label: Blog › Interviews
  name: interviews
  folder: src/site/interview
  extension: md
  editor:
    preview: false
  create: true
  i18n: true
  preview_path: /en/interview/{{slug}}
  fields:
    - { label: "Id (never change this, only set a unique value at creation)", name: id, widget: string }
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: Date, name: date, widget: datetime, i18n: true }
    - { label: "Image", name: "image", widget: "image", i18n: true }
    - { label: "Lead", name: "lead", widget: "markdown", i18n: true }
    - { label: "Body", name: "body", widget: "markdown", i18n: true }
    - label: "categories"
      name: "post_categories"
      widget: relation
      collection: post_categories
      # i18n: true
      value_field: "id"
      multiple: true
      search_fields: ["name", "id", "description"]
    - label: "author"
      name: "post_authors"
      widget: relation
      collection: post_authors
      # i18n: true
      value_field: "id"
      multiple: true
      search_fields: ["name", "id", "description"]

- label: Blog › Infographics
  name: infographic
  folder: src/site/infographic
  extension: md
  editor:
    preview: false
  create: true
  i18n: true
  preview_path: /en/infographic/{{slug}}
  fields:
    - { label: "Id (never change this, only set a unique value at creation)", name: id, widget: string }
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: Date, name: date, widget: datetime, i18n: true }
    - { label: "Lead", name: "lead", widget: "markdown", i18n: true }
    - { label: "Image", name: "image", widget: "image", i18n: true }
    - label: "categories"
      name: "post_categories"
      widget: relation
      collection: post_categories
      # i18n: true
      value_field: "id"
      multiple: true
      search_fields: ["name", "id", "description"]
    - label: "author"
      name: "post_authors"
      widget: relation
      collection: post_authors
      # i18n: true
      value_field: "id"
      multiple: true
      search_fields: ["name", "id", "description"]

- label: Blog › Categories
  name: post_categories
  folder: src/site/category
  create: true
  editor:
    preview: false
  preview_path: /en/category/{{slug}}
  identifier_field: id
  i18n: true
  # i18n:
  #   structure: single_file
  fields:
    - { label: "Id (never change this, only set a unique value at creation)", name: id, widget: string }
    - { label: "Name", name: name, widget: string, i18n: true }
    - { label: Description, name: description, widget: string, i18n: true }

- label: Blog < Category fragments>
  name: category_fragments
  folder: src/site/_includes/category_fragments
  extension: md
  editor:
    preview: false
  create: false
  i18n: true
  identifier_field: body
  fields:
    - { label: "Body ({{name}} will be replaced by category name)", name: "body", widget: "markdown", i18n: true }

- label: Blog › Authors
  name: post_authors
  folder: src/site/author
  create: true
  editor:
    preview: false
  preview_path: /en/author/{{slug}}
  identifier_field: id
  i18n: true
  # i18n:
  #   structure: single_file
  fields:
    - { label: "Id (never change this, only set a unique value at creation)", name: id, widget: string }
    - { label: "Name", name: name, widget: string, i18n: true}
    - { label: Description, name: description, widget: string, i18n: true }

- label: Blog <Author fragments>
  name: author_fragments
  folder: src/site/_includes/author_fragments
  extension: md
  editor:
    preview: false
  create: false
  i18n: true
  identifier_field: body
  fields:
    - { label: "Body ({{name}} will be replaced by author name)", name: "body", widget: "markdown", i18n: true }
# eof
