backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
- label: global texts
  name: global-texts
  i18n:
    structure: single_file
  files:
    - label: texts
      name: texts
      file: src/_data/texts.json
      i18n: true
      fields:
        - { label: Contact, name: contact, widget: string, i18n: true }
        - { label: About, name: about, widget: string, i18n: true }
        - { label: Home, name: home, widget: string, i18n: true }
        - { label: Blog, name: blog, widget: string, i18n: true }
- label: Home
  name: home
  # Configure i18n for this collection.
  folder: src/home
  extension: html
  editor:
    preview: false
  create: false
  i18n:
    structure: multiple_folders
  preview_path: /en/
  fields:
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: "Subtitle 1", name: subtitle_1, widget: string, i18n: true }
    - { label: "Paragraph 1.1", name: paragraph_1_1, widget: text, i18n: true }
    - { label: "Paragraph 1.2", name: paragraph_1_2, widget: text, i18n: true }
    - { label: "Subtitle 2", name: subtitle_2, widget: string, i18n: true }
    - { label: "Paragraph 2.1", name: paragraph_2_1, widget: text, i18n: true }
    - { label: "Paragraph 2.2", name: paragraph_2_2, widget: text, i18n: true }
- label: About us
  name: about
  folder: src/about
  extension: md
  editor:
    preview: false
  create: false
  i18n: true
  preview_path: /about/en/
  fields:
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: "Body", name: "body", widget: "markdown", i18n: true }
- label: Blog main page
  name: blog
  # Configure i18n for this collection.
  folder: src/blog
  editor:
    preview: false
  create: false
  i18n: true
  preview_path: blog/en/
  fields:
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: Introduction, name: introduction, widget: string, i18n: true }
    - { label: Tags title, name: tags_title, widget: string, i18n: true }
- label: Blog posts
  name: blog-posts
  folder: src/post
  extension: md
  editor:
    preview: false
  create: true
  i18n: true
  preview_path: /post/en/{{slug}}
  fields:
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: "Body", name: "body", widget: "markdown", i18n: true }
    - label: "tags"
      name: "post_tags"
      widget: relation
      collection: post_tags
      # i18n: true
      value_field: "name"
      multiple: true
      search_fields: ["name"]
    - label: "tagsf"
      name: "post_tagsf"
      widget: relation
      collection: post_tagsf
      value_field: "name"
      multiple: true
      search_fields: ["name"]
- label: Tags
  name: post_tags
  folder: src/tag
  create: true
  editor:
    preview: false
  preview_path: tag/en/{{slug}}
  identifier_field: name
  i18n: true
  # i18n:
  #   structure: single_file
  fields:
    - { label: Name, name: name, widget: string, i18n: true }
    - { label: Description, name: description, widget: string, i18n: true }
- label: Tags f
  name: post_tagsf
  folder: src/tagf
  create: true
  editor:
    preview: false
  preview_path: tagf/{{slug}}/en/
  identifier_field: name
  i18n:
    structure: single_file
  fields:
    - { label: Name, name: name, widget: string, i18n: true }
    - { label: Description, name: description, widget: string, i18n: true }
    - {label: "Tags", name: "tags", widget: "hidden", default: "[ en_post_tag, fr_post_tag ]"}
