backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, de, fr]

collections:
- label: "Pages"
  name: "pages"
  editor:
    preview: false
  i18n:
    structure: single_file
  files:
    - label: "Home"
      name: "home"
      file: "src/index.md"
      i18n: false
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown" }
    - label: "i18ntest"
      name: "i18ntest"
      file: "src/i18ntest.md"
      i18n: true
      fields:
        - { label: "Title", name: "title", widget: "string", i18n: true }
        - { label: "Body", name: "body", widget: "markdown", i18n: true }
  # - label: "Blog"
  #   name: "blog"
  #   folder: "src/posts"
  #   create: true
  #   editor:
  #     preview: false
  #   preview_path: posts/{{slug}}
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Description", name: "description", widget: "string" }
  #     - { label: "Author", name: "author", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "tags"
  #       name: "tags"
  #       widget: relation
  #       collection: tag
  #       value_field: name
  #       multiple: true
  #       search_fields: ["name"]
  # - label: "Tag"
  #   name: "tag"
  #   folder: "src/tag"
  #   create: true
  #   editor:
  #     preview: false
  #   preview_path: tag/{{slug}}
  #   identifier_field: name
  #   fields:
  #     - { label: "Name", name: "name", widget: "string" }
  #     - { label: "Description", name: "description", widget: "string" }

  # - label: "Settings"
  #   name: "settings"
  #   editor:
  #     preview: false
  #   files:
  #     - label: "Navigation"
  #       name: "items"
  #       file: "src/_data/navigation.yaml"
  #       fields:
  #         - label: Nav Items
  #           name: items
  #           widget: list
  #           allow_add: false
  #           collapsed: false
  #           fields:
  #             - { label: Title, name: text, widget: string }
  #             - { label: URL, name: url, widget: string }
  #     - label: "Quick Links"
  #       name: "links"
  #       file: "src/_data/quicklinks.yaml"
  #       fields:
  #         - label: Nav Items
  #           name: links
  #           widget: list
  #           collapsed: false
  #           fields:
  #             - { label: Title, name: title, widget: string }
  #             - { label: URL, name: url, widget: string }
  #             - { label: Description, name: desc, widget: string }
  #     - label: "Meta Settings"
  #       name: "settings"
  #       file: "src/_data/settings.yaml"
  #       fields:
  #         - { label: Name, name: name, widget: string }
  #         - { label: Author, name: author, widget: string }
  #         - { label: URL, name: url, widget: string }
