backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: single_file

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:

- label: Monolingual Pages
  name: monolingual-pages
  editor:
    preview: false
  files:
    - label: Home
      name: home
      file: src/mono/index.md
      i18n: false
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown" }
- label: Single File i18n Pages
  name: si-pages
  # Configure i18n for this collection.
  i18n:
    structure: single_file
  files:
    - label: About
      name: about
      file: src/multi/about.md
      editor:
        preview: false
      # Enable i18n for this file.
      i18n: true
      fields:
        - { label: Title, name: title, widget: string, i18n: true }
        - { label: "Body", name: "body", widget: "markdown", i18n: true }

- label: Multiple Folders i18n Pages
  name: i18n-pages
  # Configure i18n for this collection.
  folder: src
  extension: md
  editor:
    preview: false
  create: true
  i18n:
    structure: multiple_folders
  fields:
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: "Body", name: "body", widget: "markdown", i18n: true }
- label: Blog posts
  name: blog-posts
  # Configure i18n for this collection.
  folder: src/posts
  extension: md
  editor:
    preview: false
  create: true
  i18n:
    structure: multiple_folders
  fields:
    - { label: Title, name: title, widget: string, i18n: true }
    - { label: "Body", name: "body", widget: "markdown", i18n: true }
# - name: i18n_content
#   i18n: true
#   files:
#     - label: i18n content
#       file: src/i18ntest.md
#       i18n:
#         structure: single_file
#         locales: [en, de, fr]
#       fields:
#         - { label: "Title", name: "title", widget: "string", i18n: true }
#     - name: pages
#     label: Pages
#     # Configure i18n for this collection.
#     i18n:
#       structure: single_file
#       locales: [en, de, fr]
#     files:
#       - name: about
#         label: About Page
#         file: site/content/about.yml
#         # Enable i18n for this file.
#         i18n: true
#         fields:
#           - { label: Title, name: title, widget: string, i18n: true }# - label: "Blog"
#
  #   name: "blog"
  #   folder: "src/posts"
  #   create: true
  #   editor:
  #     preview: false
  #   preview_path: posts/{{slug}}
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Description", name: "description", widget: "string" }
  #     - { label: "Author", name: "author", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  #     - label: "tags"
  #       name: "tags"
  #       widget: relation
  #       collection: tag
  #       value_field: name
  #       multiple: true
  #       search_fields: ["name"]
  # - label: "Tag"
  #   name: "tag"
  #   folder: "src/tag"
  #   create: true
  #   editor:
  #     preview: false
  #   preview_path: tag/{{slug}}
  #   identifier_field: name
  #   fields:
  #     - { label: "Name", name: "name", widget: "string" }
  #     - { label: "Description", name: "description", widget: "string" }

  # - label: "Settings"
  #   name: "settings"
  #   editor:
  #     preview: false
  #   files:
  #     - label: "Navigation"
  #       name: "items"
  #       file: "src/_data/navigation.yaml"
  #       fields:
  #         - label: Nav Items
  #           name: items
  #           widget: list
  #           allow_add: false
  #           collapsed: false
  #           fields:
  #             - { label: Title, name: text, widget: string }
  #             - { label: URL, name: url, widget: string }
  #     - label: "Quick Links"
  #       name: "links"
  #       file: "src/_data/quicklinks.yaml"
  #       fields:
  #         - label: Nav Items
  #           name: links
  #           widget: list
  #           collapsed: false
  #           fields:
  #             - { label: Title, name: title, widget: string }
  #             - { label: URL, name: url, widget: string }
  #             - { label: Description, name: desc, widget: string }
  #     - label: "Meta Settings"
  #       name: "settings"
  #       file: "src/_data/settings.yaml"
  #       fields:
  #         - { label: Name, name: name, widget: string }
  #         - { label: Author, name: author, widget: string }
  #         - { label: URL, name: url, widget: string }
